### ISSUE TITLE
1 kHz Control Loop with Kinova Gen3: Inverse Kinematics (low level control)

### ISSUE THREAD

**Issue by pos03052** [Kinovarobotics/Kinova-kortex2_Gen3_G3L#211]
Hello,
I'm currently working on controlling a Kinova Gen3 robot at a 1-10 ms interval. I wanted to share my experience and ask for guidance on a couple of challenges I'm facing.

### Background
Initially, I tried using high-level control, but it took nearly 50 ms to receive the robot's current position and send control commands. To improve this, I switched to low-level control as suggested in the here, and I was able to reduce the control loop to 1 ms.

### Problem
To control the robot for a specific Cartesian pose, I understand that I need to solve inverse kinematics (IK) for each actuator to use low-level control. However, when I use the base->ComputeInverseKinematics method as shown in the examples, it takes approximately 20 ms on average, which is too slow for my application.

Here’s a snippet of my code:
### Code
```
k_api::Base::JointAngles USG_Kinova::getInverseKinematics(k_api::Base::BaseClient* base, float* tarPose, float* curJoint)
{
	static k_api::Base::IKData ikData;
	static k_api::Base::JointAngle* jntAngPtr[7];
	static k_api::Base::JointAngles computedJntAng;
	static bool isFirst = true;
	if (isFirst)
	{
		for (int i = 0; i < 7; i++)
		{
			jntAngPtr[i] = ikData.mutable_guess()->add_joint_angles();
		}
		isFirst = false;
		return computedJntAng;
	}

	ikData.mutable_cartesian_pose()->set_x(tarPose[0]);
	ikData.mutable_cartesian_pose()->set_y(tarPose[1]);
	ikData.mutable_cartesian_pose()->set_z(tarPose[2]);
	ikData.mutable_cartesian_pose()->set_theta_x(tarPose[5]);
	ikData.mutable_cartesian_pose()->set_theta_y(tarPose[4]);
	ikData.mutable_cartesian_pose()->set_theta_z(tarPose[3]);

	for (int i = 0; i < 7; i++)
	{
		jntAngPtr[i]->set_value(curJoint[i]);
	}
	try
	{
		computedJntAng = base->ComputeInverseKinematics(ikData);
	}
	catch (k_api::KDetailedException& ex)
	{
		std::cout << "Unable to compute inverse kinematics" << std::endl;
		printException(ex);
	}

	return computedJntAng;
}
```
### Goal
I aim to solve for the target pose using inverse kinematics, send the position commands to the robot (each actuators), and retrieve the robot’s feedback position — all within a 1-10 ms interval.

### Additional Questions
When controlling the robot with actuator position commands, is there a way to manage the robot's overall velocity or acceleration? I've come across terms like KinematicsHardLimits and SoftLimits in the documentation, but I'm not entirely clear on what they mean or how to use them effectively.

Any advice on optimizing inverse kinematics performance or clarifying the velocity/acceleration control would be greatly appreciated.

Thanks in advance!
Ethan

**Comment by pos03052** [comment]
While waiting for a response, I closely looked at some of the issues related to inverse kinematics posted here.  It seems that in low-level control, inverse kinematics calculations are not feasible unless I use some publicly available libraries or write my own code.
Could you first confirm if this understanding is correct? If so, is it possible for a robot to do a self-collision when using a custom IK code? (Of course I should handle singularities). Additionally, is it impossible to control the velocity and acceleration of robot joints in low-level control?

**Comment by martinleroux** [comment]
Hi Ethan,

I know you have already followed up on this topic in another thread and have contacted support already, but here are answers in case anyone stumbles on this issue in the future.

The ComputeInverseKinematics function uses the Base Client, which is piped via the TCP transport. The consequence of this is that _at best_ the function will return after 25ms. The function simply is not designed for real-time application. If you are building your application with C++, I recommend looking at [roboticslibrary.org](roboticslibrary.org). For Python, I recommend [Peter Corke's Robotics Toolbox for Python](https://github.com/petercorke/robotics-toolbox-python). You will also need your robot's calibration parameters to get an accurate kinematics - to get them, contact support@kinova.ca with the serial number of the arm (found on the sticker at the base - the SN in the web app is that of the controller, which is not what we are looking for).

Since you've mentioned aiming for 1-10ms, I will also highlight that if the robot is in low-level servoing mode, it will expect a command every 1ms. It can tolerate some jitter, but a 100Hz command rate will not work (or if it somehow does not trigger the internal watchdog, the performance will be terrible).

Next, the only safeties still active while in Low-level servoing mode are actuator-level safeties. This means that joint position limits still apply, but collisions between non-consecutive links will not be avoided.

Finally, in low-level, you "control" the velocity and acceleration profiles by controlling the position profile you command accordingly. The Kinematics limits change the limits applied in high level (soft limits will cause faults, hard limits would cause the actuator to shut down. Of course, soft limits must always be smaller than hard limits)

**Comment by martinleroux** [comment]
All of the above are correct.

Regarding the 1ms cycle, the robot has an internal watchdog. It will tolerate a fair amount of jitter, so as long as it runs, there isn't any major problem. If you are looking for peak performance, you could benchmark your code just to see how stable your rate really is, but monitoring your timing yourself during runtime is probably not worth the effort. If you pay attention, you can tell that the command rate is low simply by listening to the actuators - a low command rate translates to a low-frequency noise that is otherwise not there while operating in high level. It is clearly audible around 500Hz, but if you have a good ear and pay attention, even at 800Hz you can tell a difference.

The most common pitfalls concern timing. If you are just looking to prove that you can move the robot, you don't have to worry about it too much, but if you want top performance, I recommend using C++ and a real-time OS such as RTLinux. It is possible to implement low-level in Python, but make sure you have a good PC and that it is not performing other tasks at the same time. Run the cyclic in a separate thread if possible.

The next most common pitfalls only concerns low-level torque control and not position. One of the actuator safety is a Following Error, which is a mismatch between the commanded and measured joint positions. This safety is active in any control mode, so you always need to fill the position field in the command with something that makes sense (usually the feedback from the previous frame is fine). This of course is not a concern for position control since you're going to fill the field anyway.
